### ISSUE TITLE
logo offer Slim Editor

### ISSUE THREAD

**Issue by familqasimov** [replicante/SlimEditor#1]
Hi sir. I'm graphic designer. I have studied your work and I think a new design will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want I send you PR or a change please specify.

![untitled-1](https://user-images.githubusercontent.com/36432269/40257642-f941b962-5aff-11e8-9822-844549d0ebe5.png)

Best regard
Famil.

**Comment by replicante** [comment]
Thank you for your kind offer, it's a excelent work, but I intend to do the logo myself.

Best regards!!
